version: "3.7"
services:
  redis-db:
    image: redis:alpine
    command: redis-server --requirepass pass
    ports:
      - 6379:6379
    container_name: redis-db

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - redis-db
    working_dir: /opt/project      
    volumes:
      - ./backend/kubecloud.db:/app/kubecloud.db
      - ./backend/config.json:/app/config.json
      - /root/.ssh:/root/.ssh:ro
    command: ["/kubecloud", "--config", "/app/config.json"]

  frontend:
    build:
      context: frontend/kubecloud/.
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8080/api
      - VITE_STRIPE_PUBLISHABLE_KEY=""
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
