// Code generated by MockGen. DO NOT EDIT.
// Source: internal/auth/jwt.go

// Package mock_auth is a generated GoMock package.
package mock_auth

import (
	auth "kubecloud/internal/auth"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTokenManager is a mock of TokenManager interface.
type MockTokenManager struct {
	ctrl     *gomock.Controller
	recorder *MockTokenManagerMockRecorder
}

// MockTokenManagerMockRecorder is the mock recorder for MockTokenManager.
type MockTokenManagerMockRecorder struct {
	mock *MockTokenManager
}

// NewMockTokenManager creates a new mock instance.
func NewMockTokenManager(ctrl *gomock.Controller) *MockTokenManager {
	mock := &MockTokenManager{ctrl: ctrl}
	mock.recorder = &MockTokenManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenManager) EXPECT() *MockTokenManagerMockRecorder {
	return m.recorder
}

// AccessTokenFromRefresh mocks base method.
func (m *MockTokenManager) AccessTokenFromRefresh(refreshToken string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccessTokenFromRefresh", refreshToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccessTokenFromRefresh indicates an expected call of AccessTokenFromRefresh.
func (mr *MockTokenManagerMockRecorder) AccessTokenFromRefresh(refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessTokenFromRefresh", reflect.TypeOf((*MockTokenManager)(nil).AccessTokenFromRefresh), refreshToken)
}

// CreateTokenPair mocks base method.
func (m *MockTokenManager) CreateTokenPair(userID int, username string, isAdmin bool) (*auth.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTokenPair", userID, username, isAdmin)
	ret0, _ := ret[0].(*auth.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTokenPair indicates an expected call of CreateTokenPair.
func (mr *MockTokenManagerMockRecorder) CreateTokenPair(userID, username, isAdmin interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTokenPair", reflect.TypeOf((*MockTokenManager)(nil).CreateTokenPair), userID, username, isAdmin)
}

// VerifyToken mocks base method.
func (m *MockTokenManager) VerifyToken(tokenString string) (*auth.TokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyToken", tokenString)
	ret0, _ := ret[0].(*auth.TokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyToken indicates an expected call of VerifyToken.
func (mr *MockTokenManagerMockRecorder) VerifyToken(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyToken", reflect.TypeOf((*MockTokenManager)(nil).VerifyToken), tokenString)
}
