apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  # KubeCloud internal logs
  - name: Loki - KubeCloud
    type: loki
    access: proxy
    url: http://mycelium:3100
    isDefault: false
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "kubecloud"

  # Cluster VMs logs
  - name: Loki - VMs
    type: loki
    access: proxy
    url: http://mycelium:3100
    isDefault: false
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "zlog-vms"
