---
# Cilium Network Policy CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ciliumnetworkpolicies.cilium.io
spec:
  group: cilium.io
  versions:
  - name: v2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
          status:
            type: object
  scope: Namespaced
  names:
    plural: ciliumnetworkpolicies
    singular: ciliumnetworkpolicy
    kind: CiliumNetworkPolicy
    shortNames:
    - cnp
    - ciliumnp

---
# Cilium Cluster Wide Network Policy CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ciliumclusterwidenetworkpolicies.cilium.io
spec:
  group: cilium.io
  versions:
  - name: v2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
          status:
            type: object
  scope: Cluster
  names:
    plural: ciliumclusterwidenetworkpolicies
    singular: ciliumclusterwidenetworkpolicy
    kind: CiliumClusterwideNetworkPolicy
    shortNames:
    - ccnp

---
# Cilium Endpoint CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ciliumendpoints.cilium.io
spec:
  group: cilium.io
  versions:
  - name: v2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
          status:
            type: object
  scope: Namespaced
  names:
    plural: ciliumendpoints
    singular: ciliumendpoint
    kind: CiliumEndpoint
    shortNames:
    - cep
    - ciliumep

---
# Cilium Identity CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ciliumidentities.cilium.io
spec:
  group: cilium.io
  versions:
  - name: v2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
          status:
            type: object
  scope: Cluster
  names:
    plural: ciliumidentities
    singular: ciliumidentity
    kind: CiliumIdentity
    shortNames:
    - ciliumid

---
# Cilium Node CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ciliumnodes.cilium.io
spec:
  group: cilium.io
  versions:
  - name: v2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
          status:
            type: object
  scope: Cluster
  names:
    plural: ciliumnodes
    singular: ciliumnode
    kind: CiliumNode
    shortNames:
    - cn
    - cnode
